"""add document_contents and file processing status

Revision ID: 3499540d54d5
Revises: 06c607d06c48
Create Date: 2026-04-20 03:44:51.172947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3499540d54d5'
down_revision: Union[str, Sequence[str], None] = '06c607d06c48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('document_contents',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('page_index', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('is_learning_material', sa.Boolean(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_document_contents_file_id'), 'document_contents', ['file_id'], unique=False)
    op.add_column('files', sa.Column('processing_status', sa.String(length=32), nullable=False, server_default='pending'))
    op.add_column('files', sa.Column('pages_processed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('files', sa.Column('pages_total', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'pages_total')
    op.drop_column('files', 'pages_processed')
    op.drop_column('files', 'processing_status')
    op.drop_index(op.f('ix_document_contents_file_id'), table_name='document_contents')
    op.drop_table('document_contents')
    # ### end Alembic commands ###
